export interface QuizQuestion {
  id: string;
  moduleId: string;
  type: 'conceptual' | 'visual' | 'scenario' | 'prediction';
  difficulty: 'easy' | 'normal' | 'hard';
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export const quizQuestions: QuizQuestion[] = [
  {
    id: 'q1',
    moduleId: 'intro',
    type: 'conceptual',
    difficulty: 'easy',
    question: 'What does Linear Regression try to find?',
    options: [
      'The average of all data points',
      'The best straight line that fits the data',
      'The maximum value in the dataset',
      'Clusters in the data',
    ],
    correctIndex: 1,
    explanation: 'Linear Regression finds the best straight line (y = wx + b) that minimizes the distance between predictions and actual values.',
  },
  {
    id: 'q2',
    moduleId: 'math',
    type: 'conceptual',
    difficulty: 'easy',
    question: 'In the equation y = mx + b, what does "m" represent?',
    options: [
      'The y-intercept',
      'The mean of the data',
      'The slope of the line',
      'The number of data points',
    ],
    correctIndex: 2,
    explanation: 'The slope (m) determines how steep the line is. A positive slope means y increases as x increases.',
  },
  {
    id: 'q3',
    moduleId: 'math',
    type: 'prediction',
    difficulty: 'easy',
    question: 'If y = 3x + 2, what is the predicted value when x = 4?',
    options: ['10', '12', '14', '16'],
    correctIndex: 2,
    explanation: 'y = 3(4) + 2 = 12 + 2 = 14',
  },
  {
    id: 'q4',
    moduleId: 'cost',
    type: 'conceptual',
    difficulty: 'normal',
    question: 'Why do we SQUARE the errors in MSE instead of just summing them?',
    options: [
      'To make computation faster',
      'Because squared numbers are always positive',
      'So positive and negative errors do not cancel out, and large errors are penalized more',
      'It is just a convention with no mathematical reason',
    ],
    correctIndex: 2,
    explanation: 'Squaring prevents cancellation of positive/negative errors and penalizes larger errors disproportionately, making the model prioritize reducing big mistakes.',
  },
  {
    id: 'q5',
    moduleId: 'cost',
    type: 'visual',
    difficulty: 'easy',
    question: 'If you drag the regression line far away from the data points, what happens to the MSE?',
    options: [
      'It stays the same',
      'It decreases',
      'It increases dramatically',
      'It becomes negative',
    ],
    correctIndex: 2,
    explanation: 'Moving the line away increases the distance (error) to each point. Since errors are squared, the MSE increases dramatically.',
  },
  {
    id: 'q6',
    moduleId: 'gradient',
    type: 'conceptual',
    difficulty: 'normal',
    question: 'What happens if the learning rate is TOO HIGH?',
    options: [
      'The model converges faster',
      'The model overshoots the minimum and may never converge',
      'The model underfits',
      'Nothing changes',
    ],
    correctIndex: 1,
    explanation: 'A learning rate that is too high causes the optimization to take steps that are too large, overshooting the minimum and potentially diverging.',
  },
  {
    id: 'q7',
    moduleId: 'gradient',
    type: 'scenario',
    difficulty: 'normal',
    question: 'You are training a model and the loss keeps bouncing up and down without decreasing. What is the most likely cause?',
    options: [
      'The dataset is too small',
      'The learning rate is too high',
      'The model needs more features',
      'The bias term is wrong',
    ],
    correctIndex: 1,
    explanation: 'Oscillating loss typically indicates a learning rate that is too large. The optimizer is overshooting the minimum on each step.',
  },
  {
    id: 'q8',
    moduleId: 'training',
    type: 'conceptual',
    difficulty: 'easy',
    question: 'What is one "epoch" in the training process?',
    options: [
      'One update to the weights',
      'One complete pass through the entire dataset',
      'One prediction',
      'One gradient calculation',
    ],
    correctIndex: 1,
    explanation: 'An epoch is one complete pass through all training data. Multiple epochs are needed for the model to converge.',
  },
  {
    id: 'q9',
    moduleId: 'failures',
    type: 'scenario',
    difficulty: 'normal',
    question: 'A dataset contains a clear quadratic (curved) relationship. You apply Linear Regression. What happens?',
    options: [
      'It fits perfectly',
      'It underfits — the straight line cannot capture the curve',
      'It overfits',
      'The MSE becomes zero',
    ],
    correctIndex: 1,
    explanation: 'A straight line cannot capture a curved relationship. The model will underfit, producing high error on both training and test data.',
  },
  {
    id: 'q10',
    moduleId: 'failures',
    type: 'scenario',
    difficulty: 'normal',
    question: 'A dataset has one extreme outlier (a point far from all others). What effect does it have on the regression line?',
    options: [
      'No effect at all',
      'It pulls the line toward the outlier, distorting predictions for other points',
      'It improves the model accuracy',
      'It only affects the intercept',
    ],
    correctIndex: 1,
    explanation: 'MSE heavily penalizes large errors, so the optimizer will try to reduce the distance to the outlier, pulling the entire line toward it and hurting predictions for normal points.',
  },
  {
    id: 'q11',
    moduleId: 'comparison',
    type: 'conceptual',
    difficulty: 'easy',
    question: 'What is the key advantage of Linear Regression over Neural Networks?',
    options: [
      'It is more accurate',
      'It can handle nonlinear data',
      'It is simpler, faster, and more interpretable',
      'It requires more data',
    ],
    correctIndex: 2,
    explanation: 'Linear Regression is simple, fast to train, and easy to interpret. Neural Networks are more powerful but act as "black boxes" and require more data.',
  },
  {
    id: 'q12',
    moduleId: 'comparison',
    type: 'prediction',
    difficulty: 'easy',
    question: 'Which method should you try FIRST for a dataset with a clear linear trend?',
    options: [
      'Deep Neural Network',
      'Random Forest',
      'Linear Regression',
      'Convolutional Neural Network',
    ],
    correctIndex: 2,
    explanation: 'Always start simple! If the data is linear, Linear Regression will be fast, accurate, and interpretable. Only use complex models when simple ones fail.',
  },
  {
    id: 'q13',
    moduleId: 'gradient',
    type: 'conceptual',
    difficulty: 'normal',
    question: 'In Gradient Descent, the gradient tells us:',
    options: [
      'The exact location of the minimum',
      'The direction of steepest INCREASE of the loss',
      'The learning rate to use',
      'How many epochs are needed',
    ],
    correctIndex: 1,
    explanation: 'The gradient points in the direction of steepest increase. We move in the OPPOSITE direction (negative gradient) to decrease the loss.',
  },
  {
    id: 'q14',
    moduleId: 'failures',
    type: 'prediction',
    difficulty: 'normal',
    question: 'Adding heavy random noise to a dataset will likely cause:',
    options: [
      'The MSE to decrease',
      'Perfect predictions',
      'Higher MSE and less reliable predictions',
      'The model to overfit',
    ],
    correctIndex: 2,
    explanation: 'Random noise obscures the true pattern, making it harder for the model to find a good fit. This results in higher MSE and less reliable predictions.',
  },
  {
    id: 'q15',
    moduleId: 'cost',
    type: 'conceptual',
    difficulty: 'easy',
    question: 'An MSE of 0 means:',
    options: [
      'The model is terrible',
      'The model perfectly predicts every data point',
      'The model has not been trained yet',
      'There is a bug in the code',
    ],
    correctIndex: 1,
    explanation: 'MSE = 0 means every prediction exactly matches the actual value. This is rare with real data and may indicate overfitting if the data has noise.',
  },
  {
    id: 'q16',
    moduleId: 'intro',
    type: 'conceptual',
    difficulty: 'easy',
    question: 'Which type of problem is Linear Regression designed to solve?',
    options: [
      'Classification — assigning categories',
      'Regression — predicting continuous values',
      'Clustering — grouping similar items',
      'Ranking — ordering items',
    ],
    correctIndex: 1,
    explanation: 'Linear Regression is a regression algorithm. It predicts continuous numeric values (e.g., price, temperature) rather than discrete categories.',
  },
  {
    id: 'q17',
    moduleId: 'intro',
    type: 'scenario',
    difficulty: 'easy',
    question: 'You want to predict house prices based on square footage. Which approach fits best?',
    options: [
      'K-Means Clustering',
      'Linear Regression',
      'Decision Tree Classification',
      'Image recognition with CNN',
    ],
    correctIndex: 1,
    explanation: 'Predicting a continuous value (price) from a numeric feature (square footage) is a classic Linear Regression problem.',
  },
  {
    id: 'q18',
    moduleId: 'intro',
    type: 'visual',
    difficulty: 'easy',
    question: 'On a scatter plot, what does a good linear regression fit look like?',
    options: [
      'All points stacked vertically',
      'Points scattered randomly with no pattern',
      'Points roughly following a straight line with the regression line passing through them',
      'Points forming a perfect circle',
    ],
    correctIndex: 2,
    explanation: 'A good fit shows points roughly following a linear trend, with the regression line passing through the center of the point cloud, minimizing overall distance.',
  },
  {
    id: 'q19',
    moduleId: 'math',
    type: 'conceptual',
    difficulty: 'normal',
    question: 'If the slope of a regression line is negative, what does that tell us?',
    options: [
      'There is no relationship between x and y',
      'As x increases, y also increases',
      'As x increases, y decreases',
      'The model has failed',
    ],
    correctIndex: 2,
    explanation: 'A negative slope means an inverse relationship — as the input x increases, the predicted output y decreases.',
  },
  {
    id: 'q20',
    moduleId: 'math',
    type: 'prediction',
    difficulty: 'easy',
    question: 'If y = -2x + 10, what is y when x = 3?',
    options: ['4', '16', '-4', '6'],
    correctIndex: 0,
    explanation: 'y = -2(3) + 10 = -6 + 10 = 4',
  },
  {
    id: 'q21',
    moduleId: 'math',
    type: 'visual',
    difficulty: 'easy',
    question: 'What does the y-intercept (b) represent on a graph?',
    options: [
      'The steepness of the line',
      'Where the line crosses the x-axis',
      'Where the line crosses the y-axis (when x = 0)',
      'The average of all y values',
    ],
    correctIndex: 2,
    explanation: 'The y-intercept (b) is the value of y when x = 0 — the point where the regression line crosses the vertical axis.',
  },
  {
    id: 'q22',
    moduleId: 'cost',
    type: 'scenario',
    difficulty: 'normal',
    question: 'Two models have MSE of 25 and 100 respectively. Which is better and by how much?',
    options: [
      'The second model is better because 100 > 25',
      'The first model is 4x better — lower MSE means less error',
      'They are equally good',
      'Cannot be determined from MSE alone',
    ],
    correctIndex: 1,
    explanation: 'Lower MSE means less prediction error. The first model (MSE=25) has 4 times less error than the second (MSE=100), making it significantly better.',
  },
  {
    id: 'q23',
    moduleId: 'cost',
    type: 'conceptual',
    difficulty: 'normal',
    question: 'What is the "residual" in regression?',
    options: [
      'The slope of the line',
      'The difference between the actual value and the predicted value',
      'The learning rate',
      'The total number of data points',
    ],
    correctIndex: 1,
    explanation: 'A residual is the difference between an actual observed value and the value predicted by the model: residual = actual - predicted.',
  },
  {
    id: 'q24',
    moduleId: 'gradient',
    type: 'scenario',
    difficulty: 'normal',
    question: 'Your model is training very slowly, taking thousands of epochs. The loss decreases but extremely gradually. What should you do?',
    options: [
      'Decrease the learning rate',
      'Increase the learning rate',
      'Add more data points',
      'Remove the bias term',
    ],
    correctIndex: 1,
    explanation: 'Very slow convergence usually means the learning rate is too small. Increasing it will allow the optimizer to take bigger steps toward the minimum.',
  },
  {
    id: 'q25',
    moduleId: 'gradient',
    type: 'visual',
    difficulty: 'normal',
    question: 'On the cost function surface, what does the lowest point represent?',
    options: [
      'The worst possible model',
      'The starting point of training',
      'The optimal weights that minimize error',
      'The learning rate value',
    ],
    correctIndex: 2,
    explanation: 'The lowest point (global minimum) of the cost function surface represents the weight and bias values that produce the smallest prediction error.',
  },
  {
    id: 'q26',
    moduleId: 'training',
    type: 'scenario',
    difficulty: 'normal',
    question: 'After 10 epochs the loss is 500. After 100 epochs it is 50. After 200 epochs it is 49.8. What should you do?',
    options: [
      'Keep training for 1000 more epochs',
      'Stop training — the model has converged',
      'Increase the learning rate dramatically',
      'Start over with random weights',
    ],
    correctIndex: 1,
    explanation: 'The loss barely changed between epoch 100 and 200 (50 → 49.8). The model has converged. More training wastes compute for negligible improvement.',
  },
  {
    id: 'q27',
    moduleId: 'training',
    type: 'conceptual',
    difficulty: 'easy',
    question: 'What happens to the weights during each training step?',
    options: [
      'They are randomly reassigned',
      'They are updated in the direction that reduces the loss',
      'They stay the same until the final epoch',
      'They are always increased',
    ],
    correctIndex: 1,
    explanation: 'In each step, weights are adjusted by subtracting the gradient times the learning rate. This moves them in the direction that reduces the loss function.',
  },
  {
    id: 'q28',
    moduleId: 'training',
    type: 'prediction',
    difficulty: 'normal',
    question: 'If weight = 2.0 and gradient = 0.5 with learning rate = 0.1, what is the new weight?',
    options: ['2.05', '1.95', '2.5', '1.5'],
    correctIndex: 1,
    explanation: 'new_weight = old_weight - lr × gradient = 2.0 - 0.1 × 0.5 = 2.0 - 0.05 = 1.95',
  },
  {
    id: 'q29',
    moduleId: 'failures',
    type: 'conceptual',
    difficulty: 'normal',
    question: 'What is "multicollinearity" and why is it a problem?',
    options: [
      'When features are unrelated — makes the model too simple',
      'When two or more features are highly correlated — makes weight estimates unstable',
      'When there is only one feature — limits accuracy',
      'When the target variable has multiple values',
    ],
    correctIndex: 1,
    explanation: 'Multicollinearity occurs when input features are highly correlated. It makes it hard for the model to determine each feature\'s individual effect, leading to unstable weights.',
  },
  {
    id: 'q30',
    moduleId: 'failures',
    type: 'visual',
    difficulty: 'normal',
    question: 'If your data forms a U-shape (parabola), what will the regression line look like?',
    options: [
      'A perfect curve matching the data',
      'A horizontal line cutting through the middle, missing both ends',
      'A vertical line',
      'Two separate lines',
    ],
    correctIndex: 1,
    explanation: 'Linear Regression can only fit a straight line. For U-shaped data, it will draw a flat line through the middle, poorly fitting points at both extremes — a classic underfitting case.',
  },
  {
    id: 'q31',
    moduleId: 'comparison',
    type: 'scenario',
    difficulty: 'normal',
    question: 'You have 50 data points with a clear linear trend. A colleague suggests using a neural network with 10 layers. What do you recommend?',
    options: [
      'Agree — deeper is always better',
      'Use Linear Regression — it\'s sufficient and won\'t overfit',
      'Use at least 20 layers',
      'Don\'t use any model',
    ],
    correctIndex: 1,
    explanation: 'For small datasets with linear patterns, a simple Linear Regression is ideal. A deep neural network would likely overfit with only 50 points and add unnecessary complexity.',
  },
  {
    id: 'q32',
    moduleId: 'comparison',
    type: 'conceptual',
    difficulty: 'normal',
    question: 'What does "interpretability" mean in the context of models?',
    options: [
      'How fast the model trains',
      'How easily humans can understand WHY the model makes its predictions',
      'How many parameters the model has',
      'The programming language used',
    ],
    correctIndex: 1,
    explanation: 'Interpretability refers to how easily we can understand a model\'s decision-making. Linear Regression is highly interpretable: each weight directly shows a feature\'s importance and direction.',
  },
  {
    id: 'q33',
    moduleId: 'comparison',
    type: 'scenario',
    difficulty: 'normal',
    question: 'Your image recognition task needs to classify cats vs dogs. Should you use Linear Regression?',
    options: [
      'Yes — it works for everything',
      'No — this is a classification task with complex, nonlinear patterns requiring a different approach',
      'Yes, but only with a high learning rate',
      'Only if you have less than 100 images',
    ],
    correctIndex: 1,
    explanation: 'Image classification involves complex nonlinear patterns and categorical outputs. Linear Regression predicts continuous values and can\'t capture the complexity of images. A CNN or similar classifier is needed.',
  },
  // --- Hard questions ---
  {
    id: 'q34',
    moduleId: 'intro',
    type: 'scenario',
    difficulty: 'hard',
    question: 'You have a dataset with 3 features: temperature, humidity, and "temperature × 2". You apply multiple linear regression. What problem will you encounter?',
    options: [
      'The model will train faster',
      'Perfect multicollinearity — the design matrix is singular and the closed-form solution fails',
      'The model will overfit',
      'The MSE will be negative',
    ],
    correctIndex: 1,
    explanation: 'The third feature is an exact linear combination of the first. This creates perfect multicollinearity, making (XᵀX) singular (non-invertible), so the normal equation has no unique solution.',
  },
  {
    id: 'q35',
    moduleId: 'math',
    type: 'prediction',
    difficulty: 'hard',
    question: 'The normal equation for linear regression is w = (XᵀX)⁻¹Xᵀy. If X is a 100×3 matrix, what is the shape of w?',
    options: ['100×1', '3×1', '3×100', '1×3'],
    correctIndex: 1,
    explanation: 'XᵀX is 3×3, its inverse is 3×3. Xᵀy is 3×1. So w = (3×3)(3×1) = 3×1. One weight per feature.',
  },
  {
    id: 'q36',
    moduleId: 'math',
    type: 'conceptual',
    difficulty: 'hard',
    question: 'Why does the closed-form solution (normal equation) become impractical for very large datasets?',
    options: [
      'It requires more training epochs',
      'Inverting XᵀX has O(n³) complexity in the number of features, which is too slow for high-dimensional data',
      'It always underfits',
      'It cannot handle negative values',
    ],
    correctIndex: 1,
    explanation: 'The normal equation requires computing (XᵀX)⁻¹, which has O(p³) time complexity where p is the number of features. For millions of features, this becomes computationally infeasible — gradient descent is preferred.',
  },
  {
    id: 'q37',
    moduleId: 'cost',
    type: 'conceptual',
    difficulty: 'hard',
    question: 'MSE uses squared errors. MAE (Mean Absolute Error) uses absolute errors. When would you prefer MAE over MSE?',
    options: [
      'When you want to penalize large errors more',
      'When your data has many outliers and you want the model to be robust to them',
      'When you need a differentiable loss function',
      'Always — MAE is strictly better',
    ],
    correctIndex: 1,
    explanation: 'MAE treats all errors linearly, so outliers don\'t disproportionately dominate the loss. MSE squares errors, making the model chase outliers. MAE is more robust when outliers are present.',
  },
  {
    id: 'q38',
    moduleId: 'cost',
    type: 'prediction',
    difficulty: 'hard',
    question: 'Given points (1,2), (2,4), (3,5) and the line y = 1.5x + 0.5, what is the MSE?',
    options: ['0', '0.0833', '0.25', '0.5'],
    correctIndex: 1,
    explanation: 'Predictions: y₁=2, y₂=3.5, y₃=5. Errors: (2-2)²=0, (4-3.5)²=0.25, (5-5)²=0. MSE = (0 + 0.25 + 0) / 3 = 0.0833.',
  },
  {
    id: 'q39',
    moduleId: 'gradient',
    type: 'conceptual',
    difficulty: 'hard',
    question: 'What is the partial derivative of MSE = (1/n)Σ(wxᵢ + b - yᵢ)² with respect to w?',
    options: [
      '(2/n)Σ(wxᵢ + b - yᵢ)',
      '(2/n)Σ(wxᵢ + b - yᵢ) × xᵢ',
      '(1/n)Σxᵢ',
      '(2/n)Σyᵢ',
    ],
    correctIndex: 1,
    explanation: 'By the chain rule: ∂MSE/∂w = (2/n)Σ(wxᵢ + b - yᵢ) × xᵢ. The error term is multiplied by xᵢ because w is multiplied by x in the prediction.',
  },
  {
    id: 'q40',
    moduleId: 'gradient',
    type: 'scenario',
    difficulty: 'hard',
    question: 'You plot the loss curve and notice it decreases, then increases, then decreases again in a zigzag pattern. The overall trend is downward but unstable. What is the best fix?',
    options: [
      'Use a larger learning rate',
      'Use learning rate decay — start high and gradually reduce it',
      'Remove all features',
      'Use MSE instead of MAE',
    ],
    correctIndex: 1,
    explanation: 'A zigzag loss with a downward trend suggests the learning rate is slightly too large. Learning rate scheduling (decay) starts with larger steps for fast initial progress, then reduces the rate for stable convergence.',
  },
  {
    id: 'q41',
    moduleId: 'training',
    type: 'conceptual',
    difficulty: 'hard',
    question: 'What is the difference between batch gradient descent, mini-batch gradient descent, and stochastic gradient descent (SGD)?',
    options: [
      'They use different loss functions',
      'Batch uses all data per update, mini-batch uses a subset, SGD uses a single sample',
      'SGD is always faster and more accurate',
      'There is no practical difference',
    ],
    correctIndex: 1,
    explanation: 'Batch GD computes the gradient over the entire dataset (slow but stable). Mini-batch uses a subset (balanced). SGD uses one sample per update (fast but noisy). Most real training uses mini-batch.',
  },
  {
    id: 'q42',
    moduleId: 'training',
    type: 'prediction',
    difficulty: 'hard',
    question: 'A model trained for 50 epochs has training MSE=10 and test MSE=100. What is happening?',
    options: [
      'The model is underfitting',
      'The model is overfitting — it memorized training data but doesn\'t generalize',
      'The model is perfectly trained',
      'The test set is too large',
    ],
    correctIndex: 1,
    explanation: 'A large gap between training error (10) and test error (100) is the hallmark of overfitting. The model fits training data well but fails on unseen data. Regularization or more data can help.',
  },
  {
    id: 'q43',
    moduleId: 'failures',
    type: 'scenario',
    difficulty: 'hard',
    question: 'Your linear regression has R² = 0.15. What does this mean and what should you do?',
    options: [
      'The model explains 85% of variance — it\'s great',
      'The model explains only 15% of variance — the relationship is likely nonlinear or key features are missing',
      'R² of 0.15 is always acceptable',
      'The model has converged optimally',
    ],
    correctIndex: 1,
    explanation: 'R² measures the proportion of variance explained. 0.15 means only 15% of the variation in y is explained by x. The remaining 85% is unexplained — try adding features, polynomial terms, or a different model.',
  },
  {
    id: 'q44',
    moduleId: 'failures',
    type: 'conceptual',
    difficulty: 'hard',
    question: 'What is heteroscedasticity, and why does it violate linear regression assumptions?',
    options: [
      'When the mean of errors is non-zero',
      'When the variance of residuals changes across different values of x, violating the constant-variance assumption',
      'When errors are correlated with each other',
      'When the data has too few points',
    ],
    correctIndex: 1,
    explanation: 'Linear regression assumes homoscedasticity (constant error variance). Heteroscedasticity means error spread changes with x (e.g., wider scatter for larger x), making confidence intervals and p-values unreliable.',
  },
  {
    id: 'q45',
    moduleId: 'comparison',
    type: 'conceptual',
    difficulty: 'hard',
    question: 'What is regularization (L1/L2), and why would you add it to linear regression?',
    options: [
      'It increases the learning rate for faster training',
      'It adds a penalty term to the loss to prevent weights from becoming too large, reducing overfitting',
      'It removes outliers from the dataset',
      'It converts regression into classification',
    ],
    correctIndex: 1,
    explanation: 'Regularization adds λ||w||² (L2/Ridge) or λ||w||₁ (L1/Lasso) to the loss function. This penalizes large weights, encouraging simpler models that generalize better and reducing overfitting.',
  },
  {
    id: 'q46',
    moduleId: 'comparison',
    type: 'scenario',
    difficulty: 'hard',
    question: 'You apply Ridge Regression (L2) with λ=1000. What happens to the weights?',
    options: [
      'They become very large',
      'They are pushed very close to zero, severely underfitting the data',
      'They are unaffected',
      'They become negative',
    ],
    correctIndex: 1,
    explanation: 'A very high regularization parameter (λ=1000) adds enormous penalty for non-zero weights. The optimizer minimizes this by pushing all weights toward zero, effectively flattening the line and underfitting.',
  },
  {
    id: 'q47',
    moduleId: 'cost',
    type: 'scenario',
    difficulty: 'hard',
    question: 'You compute the gradient of MSE and find that ∂L/∂w = 0 and ∂L/∂b = 0. What does this tell you?',
    options: [
      'The model hasn\'t started training yet',
      'The current w and b are at a critical point (minimum) of the loss function',
      'The learning rate is zero',
      'The data has no pattern',
    ],
    correctIndex: 1,
    explanation: 'When all partial derivatives are zero, you\'re at a stationary point. For MSE (which is convex for linear regression), this is the global minimum — the optimal weights have been found.',
  },
  {
    id: 'q48',
    moduleId: 'intro',
    type: 'conceptual',
    difficulty: 'hard',
    question: 'Linear Regression assumes a linear relationship between inputs and outputs. Which of these relationships can it still model correctly?',
    options: [
      'y = sin(x)',
      'y = 3x₁² + 2x₂ (if x₁² is given as a feature)',
      'y = e^x',
      'y = x₁ × x₂ (interaction without feature engineering)',
    ],
    correctIndex: 1,
    explanation: 'Linear regression is linear in its PARAMETERS, not its features. If you provide x₁² as a pre-computed feature, the model treats it as just another input and fits y = w₁(x₁²) + w₂x₂ + b perfectly. Feature engineering expands what LR can model.',
  },
  {
    id: 'q49',
    moduleId: 'training',
    type: 'scenario',
    difficulty: 'hard',
    question: 'Your features have very different scales: x₁ ∈ [0, 1] and x₂ ∈ [0, 1000000]. You run gradient descent without normalization. What happens?',
    options: [
      'Nothing — gradient descent handles all scales equally',
      'The loss surface becomes elongated, causing slow zigzag convergence and requiring a very small learning rate',
      'The model only learns x₂ and ignores x₁',
      'The MSE becomes negative',
    ],
    correctIndex: 1,
    explanation: 'Unscaled features create an elongated (elliptical) loss surface. The gradient is dominated by the large-scale feature, causing inefficient zigzag steps. Feature normalization makes the surface more spherical, enabling faster convergence.',
  },
  {
    id: 'q50',
    moduleId: 'gradient',
    type: 'prediction',
    difficulty: 'hard',
    question: 'For a single data point (x=2, y=6) with current w=1 and b=0, what is ∂MSE/∂w?',
    options: ['-16', '-8', '8', '16'],
    correctIndex: 0,
    explanation: 'Prediction: ŷ = 1×2 + 0 = 2. Error: ŷ - y = 2 - 6 = -4. ∂MSE/∂w = 2(ŷ-y)×x = 2(-4)(2) = -16. The negative gradient means w should increase (move right to reduce loss).',
  },
];

export function getQuizByModule(moduleId: string): QuizQuestion[] {
  return quizQuestions.filter(q => q.moduleId === moduleId);
}

export function getQuizTypeLabel(type: QuizQuestion['type']): string {
  const labels = {
    conceptual: '💡 Conceptual',
    visual: '👁️ Visual',
    scenario: '🎬 Scenario',
    prediction: '🔮 Prediction',
  };
  return labels[type];
}

export function getDifficultyLabel(difficulty: QuizQuestion['difficulty']): { label: string; color: string } {
  const map = {
    easy: { label: '🟢 Easy', color: 'text-success bg-success/10 border-success/20' },
    normal: { label: '🟡 Normal', color: 'text-warning bg-warning/10 border-warning/20' },
    hard: { label: '🔴 Hard', color: 'text-error bg-error/10 border-error/20' },
  };
  return map[difficulty];
}
